-- ESTRUTURAS DAS TABELAS
-- Criando o banco CLINICA
CREATE DATABASE CLINICA
USE CLINICA
CREATE TABLE MEDICOS
(
CODM VARCHAR(7) NOT NULL,
NOMEM VARCHAR(30) NOT NULL,
IDADE INTEGER NOT NULL,
ESPECIALIDADE VARCHAR(30)NOT NULL,
PRIMARY KEY (CODM)
)
CREATE TABLE PACIENTES
(
CODP VARCHAR(7) NOT NULL,
NOMEP VARCHAR(30) NOT NULL,
PRIMARY KEY (CODP)
)
CREATE TABLE CONSULTAS
(
CODM VARCHAR(7) NOT NULL,
CODP VARCHAR(7) NOT NULL,
DATA DATE NOT NULL,
HORA INTEGER NOT NULL,
)

-- INSERIR MEDICOS

INSERT INTO MEDICOS (CODM, NOMEM, IDADE, ESPECIALIDADE)
VALUES('M1','Jo�o',33,'Traumatlogia');

INSERT INTO MEDICOS (CODM, NOMEM, IDADE, ESPECIALIDADE)
VALUES('M2','Paolo',28,'Cl�nica Geral');

INSERT INTO MEDICOS (CODM, NOMEM, IDADE, ESPECIALIDADE)
VALUES('M3','Marta',30,'Obstetr�cia');

INSERT INTO MEDICOS (CODM, NOMEM, IDADE, ESPECIALIDADE)
VALUES('M4','Carlos',33,'Nefrologista');

INSERT INTO MEDICOS (CODM, NOMEM, IDADE, ESPECIALIDADE)
VALUES('M5','Lucas',28,'Psiquiatra');

INSERT INTO MEDICOS (CODM, NOMEM, IDADE, ESPECIALIDADE)
VALUES('M6','Erickson',30,'Reumatologista');

--INSERIR PACIENTE

INSERT INTO PACIENTES (CODP, NOMEP)
VALUES('P1','Charles');

INSERT INTO PACIENTES (CODP, NOMEP)
VALUES('P2','Raimunda');

INSERT INTO PACIENTES (CODP, NOMEP)
VALUES('P3','Simone');

INSERT INTO PACIENTES (CODP, NOMEP)
VALUES('P4','Gutierrez');

INSERT INTO PACIENTES (CODP, NOMEP)
VALUES('P5','Rosana');

INSERT INTO PACIENTES (CODP, NOMEP)
VALUES('P6','Marta');

INSERT INTO PACIENTES (CODP, NOMEP)
VALUES('P7','Marcos');

INSERT INTO PACIENTES (CODP, NOMEP)
VALUES('P8','Rodrigo');

INSERT INTO PACIENTES (CODP, NOMEP)
VALUES('P9','Michele');

INSERT INTO PACIENTES (CODP, NOMEP)
VALUES('P10','Sônia');

--INSERIR CONSULTAS
 
INSERT INTO CONSULTAS (CODM, CODP, DATA, HORA)
VALUES('M1','P1','15/03/2022','14');

INSERT INTO CONSULTAS (CODM, CODP, DATA, HORA)
VALUES('M1','P3','20/03/2022','15');

INSERT INTO CONSULTAS (CODM, CODP, DATA, HORA)
VALUES('M2','P2','26/03/2022','17');

INSERT INTO CONSULTAS (CODM, CODP, DATA, HORA)
VALUES('M3','P3','03/03/2022','16');

INSERT INTO CONSULTAS (CODM, CODP, DATA, HORA)
VALUES('M4','P1','05/05/2022','14');

INSERT INTO CONSULTAS (CODM, CODP, DATA, HORA)
VALUES('M5','P3','20/05/2022','15');

INSERT INTO CONSULTAS (CODM, CODP, DATA, HORA)
VALUES('M4','P2','26/05/2022','17');

INSERT INTO CONSULTAS (CODM, CODP, DATA, HORA)
VALUES('M5','P3','27/05/2022','16');

INSERT INTO CONSULTAS (CODM, CODP, DATA, HORA)
VALUES('M6','P1','12/05/2022','14');

INSERT INTO CONSULTAS (CODM, CODP, DATA, HORA)
VALUES('M5','P3','25/05/2022','15');

INSERT INTO CONSULTAS (CODM, CODP, DATA, HORA)
VALUES('M3','P2','14/05/2022','17');

INSERT INTO CONSULTAS (CODM, CODP, DATA, HORA)
VALUES('M4','P3','25/05/2022','16');

INSERT INTO CONSULTAS (CODM, CODP, DATA, HORA)
VALUES('M1','P4','12/05/2022','14');

INSERT INTO CONSULTAS (CODM, CODP, DATA, HORA)
VALUES('M2','P5','25/05/2022','15');

INSERT INTO CONSULTAS (CODM, CODP, DATA, HORA)
VALUES('M5','P3','14/05/2022','17');

INSERT INTO CONSULTAS (CODM, CODP, DATA, HORA)
VALUES('M6','P1','24/05/2022','16');

SELECT * FROM MEDICOS
SELECT * FROM PACIENTES
SELECT * FROM CONSULTAS        

-- Criando uma view chamada VW_DadosPac
-- copiando a coluna nomep e codp da tabela Pacientes
-- O que é uma view?
-- 
CREATE VIEW VW_DadosPac AS 
SELECT codp, nomep FROM PACIENTES

-- selecionando todos os pacientes que possuem um i no nome
SELECT nomep FROM VW_DadosPac
WHERE nomep like '%i%'

SELECT * FROM VW_DadosPac
SELECT * FROM PACIENTES

-- Criando a view MedCons unindo tabela medico e consultas
CREATE VIEW VW_MedCons AS 
SELECT	m.nomem,
		c.data,
		c.hora
FROM MEDICOS AS m
INNER JOIN CONSULTAS c
ON c.CODM = m.CODM

-- CRIANDO VIEW JA FORMATADA
CREATE VIEW VW_MedCons AS 
SELECT	m.nomem AS NOME_MEDICO,
		CONVERT(CHAR(10), c.data, 103) AS DATA_CONSULTA,
		c.hora AS HORARIO
FROM MEDICOS AS m
INNER JOIN CONSULTAS c
ON c.CODM = m.CODM

-- FORMATANDO A DATA EM UM SELECT
SELECT	NOMEM AS NOME_MEDICO,
		CONVERT(CHAR(10), DATA, 103) AS DIA_CONSULTA,
		HORA AS HORARIO
FROM VW_MedCons
ORDER BY 1, 2, 3

-- OBS: COMANDOS DML EM UMA VIEW REFLETEM NA TABELA F�SICA
SELECT * FROM VW_MedCons
SELECT * FROM MEDICOS

UPDATE VW_MedCons
SET NOME_MEDICO = 'Paulo'
WHERE NOME_MEDICO LIKE 'Paolo'

-- BUSCANDO PACIENTES QUE TENHAM O NOME INCIADO COM A LETRA M
-- Uma view ao ser consultada, o sistema tradutor aponta dinamicamento para a tabela fixa

-- BUSCANDO O NOME DO M�DICO QUE TENHA CONSULTAS PARA O MES DE MAIO A PARTIR DAS 16HRS
SELECT	NOME_MEDICO,
		DATA_CONSULTA,
		HORARIO
FROM VW_MedCons
WHERE	MONTH(DATA_CONSULTA) = 5 AND 
		YEAR(DATA_CONSULTA) = 2022 AND 
		HORARIO >= '16'

-- BANCO: SERRA
-- VIEW PARA EXIBIR LISTA DE PREÇOS NA ORDEM ALFABETICA CONTENDO CODIGO, NOME, PRECO_VAREJO, 
CREATE VIEW VW_Produtos AS
SELECT	PRO_CODIGO,
		PRO_NOME,
		PRO_PRECO_VAREJO,
		(PRO_PRECO_VAREJO * 0.8) AS PROMOCAO
FROM PRODUTOS 

SELECT * FROM VW_Produtos

-- --------------------------
CREATE VIEW VW_PessoaFJ AS
SELECT	CAD_TIPO_PESSOA,
		CAD_CPF AS CPF_CNPJ,
		CAD_NOME
FROM CADASTROS
WHERE	CAD_CPF IS NOT NULL AND 
		CAD_NOME LIKE 'ES%'
UNION
SELECT	CAD_TIPO_PESSOA,
		CAD_CNPJ,
		CAD_NOME
FROM CADASTROS
WHERE	CAD_CNPJ IS NOT NULL AND 
		CAD_NOME LIKE 'ES%'

SELECT * FROM VW_PessoaFJ

-- COLOCAR CARGA DE NEGOCIO NO SQL